name: CI
on:
    pull_request:
        branches:
            - main
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: python --version
            - name: verifica sintaxe
              run:
                python -m compileall .